services:
  - type: web
    name: hostel-finder
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostel-finder-db
          property: connectionString

databases:
  - name: hostel-finder-db
    plan: free
    databaseName: hostel_finder
    user: hostel_user
